apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: autoprotocoltrans
type: Opaque
stringData:
  # 数据库用户名
  datasource-username: "root"
  # 数据库密码（从 MySQL Secret 引用，或单独设置）
  datasource-password: "123456"



