apiVersion: v1
kind: Service
metadata:
  name: autoprotocoltrans-app
  namespace: autoprotocoltrans
  labels:
    app: autoprotocoltrans-app
spec:
  type: ClusterIP  # 可以使用 LoadBalancer 或 NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: autoprotocoltrans-app










