apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: autoprotocoltrans
data:
  # MySQL 字符集配置
  character-set-server: "utf8mb4"
  collation-server: "utf8mb4_unicode_ci"
  default-authentication-plugin: "mysql_native_password"
  # 时区
  TZ: "Asia/Shanghai"




