apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: autoprotocoltrans
type: Opaque
stringData:
  # MySQL root 密码
  root-password: "123456"
  # MySQL 数据库名
  database: "protovol_trans"
  # MySQL 用户名
  username: "root"
  # MySQL 用户密码（如果使用独立用户）
  password: "123456"









